#!/usr/bin/env python3
"""
Test why Google Meet button isn't showing in Calendar events
"""

import os
from datetime import datetime, timedelta
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

load_dotenv()

CRED_FILE = os.getenv("GOOGLE_CREDENTIALS_FILE", "noori-credential-file.json")

def test_google_meet_generation():
    """Test if Google Meet link is generated properly"""
    
    try:
        credentials = Credentials.from_service_account_file(
            CRED_FILE,
            scopes=['https://www.googleapis.com/auth/calendar']
        )
        
        service = build('calendar', 'v3', credentials=credentials)
        
        print("=" * 70)
        print("Testing Google Meet Link Generation")
        print("=" * 70)
        
        # Create event WITH attendees (this helps Google Meet generation)
        now = datetime.utcnow()
        start = now + timedelta(hours=1)
        end = start + timedelta(hours=1)
        
        service_account_email = "noori-portal-bot@noori-487922.iam.gserviceaccount.com"
        
        event = {
            "summary": "Test Google Meet Class",
            "description": "Testing Google Meet link generation",
            "start": {
                "dateTime": start.isoformat() + "Z",
                "timeZone": "UTC",
            },
            "end": {
                "dateTime": end.isoformat() + "Z",
                "timeZone": "UTC",
            },
            "visibility": "public",
            # Add attendees to help Google Meet generation
            "attendees": [
                {
                    "email": service_account_email,
                    "responseStatus": "accepted"
                }
            ],
            "conferenceData": {
                "createRequest": {
                    "requestId": f"test-{start.timestamp()}",
                    "conferenceSolution": {
                        "key": {
                            "conferenceSolution": "hangoutsMeet"
                        }
                    }
                }
            }
        }
        
        print("\nCreating event WITH attendees...")
        result = service.events().insert(
            calendarId='primary',
            body=event,
            conferenceDataVersion=1,
            sendNotifications=False
        ).execute()
        
        event_id = result.get("id")
        html_link = result.get("htmlLink")
        
        print(f"\n✅ Event Created: {event_id}")
        print(f"Public Link: {html_link}")
        
        # Check for conference data
        if "conferenceData" in result:
            conf = result["conferenceData"]
            print(f"\n📞 Conference Data Found:")
            print(f"   Solution: {conf.get('conferenceSolution', {}).get('name')}")
            
            entry_points = conf.get("entryPoints", [])
            if entry_points:
                print(f"   Entry Points ({len(entry_points)}):")
                for ep in entry_points:
                    print(f"     - Type: {ep.get('entryPointType')}")
                    print(f"       URI: {ep.get('uri')}")
            else:
                print(f"   ⚠️ No entry points yet (Google Meet will add later)")
                print(f"   📌 The 'Join with Google Meet' button will appear in Calendar in 1-2 minutes")
        else:
            print(f"\n❌ No conference data in response")
            print(f"Google Meet link will be auto-generated by Calendar")
        
        # Get event details
        print(f"\nRetrieving event details...")
        details = service.events().get(calendarId='primary', eventId=event_id).execute()
        
        if "conferenceData" in details and details["conferenceData"].get("entryPoints"):
            print(f"✅ Google Meet link is now available:")
            for ep in details["conferenceData"]["entryPoints"]:
                if ep.get("entryPointType") == "video":
                    print(f"   {ep.get('uri')}")
        else:
            print(f"ℹ️  Google Meet link will be auto-added by Google Calendar")
        
        print(f"\nAccess the event here:")
        print(f"{html_link}")
        
        # Cleanup
        service.events().delete(calendarId='primary', eventId=event_id).execute()
        print(f"\n✅ Test event cleaned up")
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_google_meet_generation()
